### ISSUE TITLE
Please Publish 1.19.3 Build on Modrinth

### ISSUE THREAD

**Issue by sternschnaube** [IMB11/MRU#2]
Hello, the file for mru-0.1.5+1.19.3 is not available on Modrinth yet.
And please change the "Client side" information on Modrinth to "Optional", for "Snow Under Trees" and "Illagers Love Armor".
They can be used pure server-side, saying "Requiered" misleads people 😊

Thanks for mainting and bringing us "Snow Under Tree" to the newest version.

**Comment by IMB11** [comment]
Ah, oops, Autopublish hasn't been publishing. I'll get that done now.

**Comment by venaminecraft** [comment]
Thank you.
