### ISSUE TITLE
lack of 1.19.3 or 1.19.4 MRU

### ISSUE THREAD

**Issue by ColonelGerdauf** [IMB11/MRU#3]
As it currently stands "Snow Under Trees" is currently unplayable under those versions, despite the fact that the mod has been published under those versions. The mod claims that MRU is a needed dependency, and yet it isn't listed in Modrinth.

**Comment by IMB11** [comment]
god I wish people told me earlier.... fixing.

**Comment by IMB11** [comment]
Buildscript failed

**Comment by IMB11** [comment]
1.19.3 seems to have uploaded though, only missing 1.19.4 https://modrinth.com/mod/mru/version/0.1.5+1.19.3

**Comment by IMB11** [comment]
Actually, the 1.19.3 version should work on 1.19.4 - closing and updating modrinth
