### ISSUE TITLE
Switch to fabric-api mod ID for Fabric API

### ISSUE THREAD

**Issue by Poopooracoocoo** [IMB11/MRU#6]
It's clearer and you don't seem to update the older versions of MC where Fabric API only had the "fabric" mod ID. 

Ref https://github.com/IMB11/MRU/blob/main/src/main/resources/fabric.mod.json#L30

**Comment by IMB11** [comment]
It's a bit of a nitpick, but you're probably right, I'll switch it when I update MRU in the future

**Comment by IMB11** [comment]
FabricAPI still does "provides": [... "fabric"]

**Comment by Poopooracoocoo** [comment]
Why do you choose to use the old ID? Are there any benefits? You don't backport to very old versions of Minecraft. Users continue to be confused.

**Comment by Nucceteere** [comment]
I think most Fabric users know they should have Fabric API for %90 of their mods to work.
