### ISSUE TITLE
don't fetch http on main thread

### ISSUE THREAD

**Issue by SettingDust** [IMB11/MRU#7]
Make the launch slower

**Comment by IMB11** [comment]
No HTTP requests are done on launch, nothing is done on launch by MRU

**Comment by SettingDust** [comment]
https://github.com/IMB11/Sounds/blob/main/src/main/java/dev/imb11/sounds/SoundsClient.java#L53

https://github.com/IMB11/MRU/blob/main/src/main/java/dev/imb11/mru/API.java#L36-L39

**Comment by IMB11** [comment]
That's a Sounds issue then, not a MRU one.

**Comment by IMB11** [comment]
I'll look into it.
